import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import AppNavBar from "@/components/AppNavBar";
import { ThemeProvider } from "@/components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider
        appearance={{
          baseTheme: undefined,
          variables: {
            colorPrimary: "#3b82f6",
            colorBackground: "#000000",
            colorInputBackground: "#1a1a1a",
            colorInputText: "#ffffff",
            colorText: "#ffffff",
            colorTextSecondary: "#9ca3af",
            colorShimmer: "#1f2937",
            colorNeutral: "#374151",
            colorDanger: "#ef4444",
            colorSuccess: "#10b981",
            colorWarning: "#f59e0b",
          },
          elements: {
            modalContent: {
              backgroundColor: "#000000",
              border: "1px solid #374151",
              borderRadius: "16px",
              boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.8)",
            },
            modalCloseButton: {
              color: "#9ca3af",
              "&:hover": {
                color: "#ffffff",
              },
            },
            card: {
              backgroundColor: "#000000",
              border: "1px solid #374151",
              borderRadius: "12px",
            },
            headerTitle: {
              color: "#ffffff",
            },
            headerSubtitle: {
              color: "#9ca3af",
            },
            socialButtonsBlockButton: {
              backgroundColor: "#1a1a1a",
              border: "1px solid #374151",
              color: "#ffffff",
              "&:hover": {
                backgroundColor: "#2d2d2d",
              },
            },
            formButtonPrimary: {
              backgroundColor: "#3b82f6",
              border: "none",
              "&:hover": {
                backgroundColor: "#2563eb",
              },
            },
            formFieldInput: {
              backgroundColor: "#1a1a1a",
              border: "1px solid #374151",
              color: "#ffffff",
              "&:focus": {
                borderColor: "#3b82f6",
                boxShadow: "0 0 0 2px rgba(59, 130, 246, 0.2)",
              },
            },
            formFieldLabel: {
              color: "#e5e7eb",
            },
            footerActionText: {
              color: "#9ca3af",
            },
            footerActionLink: {
              color: "#3b82f6",
              "&:hover": {
                color: "#2563eb",
              },
            },
            dividerLine: {
              backgroundColor: "#374151",
            },
            dividerText: {
              color: "#9ca3af",
            },
          },
        }}
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
              storageKey="uptime-theme"
          >
            <AppNavBar />
            <main className="pt-24">
              {children}
            </main>
          </ThemeProvider>
        </body>
      </ClerkProvider>
    </html>
  );
}
